version: '3.8'
services:
    mongo-db:
        image: mongo:6.0.6
        restart: always
        container_name: mongo-db
        ports:
            - '27017:27017'
        volumes:
            - ./mongo:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    postgres:
        image: postgres:15.3
        restart: always
        container_name: postgres
        ports:
            - '5432:5432'
        volumes:
            - ./postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB_NAME}
